local gooList = easyEdit.enemyList:add("Goos")
gooList:addEnemy("Meta_shapeshifter","Unique")
gooList:addEnemy("Meta_spikygoo","Unique")
gooList:addEnemy("Meta_nestedgoo","Core")
gooList:addEnemy("Meta_splittinggoo","Core")
gooList:addEnemy("Meta_pylongoo","Unique")
gooList:addEnemy("Meta_sludgegoo","Core")
gooList:addEnemy("Snowtank", "Bots")
gooList:addEnemy("Snowart", "Bots")
gooList:addEnemy("Snowlaser", "Bots")
gooList:addEnemy("Jelly_Health", "Leaders")
gooList:addEnemy("Jelly_Regen", "Leaders")
gooList:addEnemy("Jelly_Armor", "Leaders")
gooList:addEnemy("Jelly_Explode", "Leaders")
gooList:addEnemy("Jelly_Spider", "Leaders")
gooList:addEnemy("Jelly_Fire", "Leaders")
gooList:addEnemy("Jelly_Boost", "Leaders")